version: '3'
services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: Materia
    volumes:
      - ./postgres:/var/lib/postgresql/data
